### ISSUE TITLE
Missing DNS records for services not using default apps domain

### ISSUE THREAD

**Issue by 54nd20** [appuio/terraform-openshift4-exoscale#44]
When not using the default apps domain for services like the console, like it is done on APPUiO Cloud, the terraform module does not create DNS records for those. When setting up a cluster for APPUiO Cloud, the following records are missing:
`cname.basedomain  IN CNAME cname.apps.basedomain`
`api.basedomain IN CNAME cname.apps.basedomain`
`console.basedomain IN CNAME cname.apps.basedomain`
`registry.basedomain IN CNAME cname.apps.basedomain`

**Comment by simu** [comment]
Those CNAME records are not standard for APPUiO Managed OpenShift 4 (cf. https://kb.vshn.ch/oc4/explanations/dns_scheme.html), so we won't add a variable to this Terraform module to create them. Instead, we'll add a set of `exo` CLI commands to the APPUiO Cloud zone setup how-to to create those records, see https://github.com/appuio/appuio-io-docs/issues/99.
